# Generated by Django 5.0.6 on 2024-05-14 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('page', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('course_id', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('org_id', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('get_data', models.JSONField(blank=True, null=True)),
                ('has_get', models.BooleanField(blank=True, null=True)),
                ('post_data', models.JSONField(blank=True, null=True)),
                ('has_post', models.BooleanField(blank=True, null=True)),
                ('session', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('agent', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('referer', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('accept_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_log.acceptlanguage')),
                ('event_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_log.eventsource')),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_log.eventtype')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_log.host')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_log.user')),
            ],
        ),
    ]
