# Generated by Django 5.0.6 on 2024-05-14 23:30

from django.db import migrations
from event_log.models import EventLog 
import json
from django.http import JsonResponse

def creat_event_logs_from_json(apps, schema_editor):
    # Ruta al archivo JSON (por ejemplo, dentro del directorio de medios)
    json_file_path = 'event_log/static/oneday_data.json'

    # Intentar abrir y leer el archivo JSON
    with open(json_file_path, 'r') as json_file:
        data = json.load(json_file)
        num_elements = len(data["context"])
        for i in range(0, num_elements):
            context=data["context"][str(i)]
            username=data["username"][str(i)]              
            session=data["session"][str(i)]
            agent=data["agent"][str(i)]
            host=data["host"][str(i)]
            referer=data["referer"][str(i)]
            accept_language=data["accept_language"][str(i)]
            event=data["event"][str(i)]
            time=data["time"][str(i)]
            event_type=data["event_type"][str(i)]
            event_source=data["event_source"][str(i)]              
            page=data["page"][str(i)]
            EventLog.objects.create(
                context=context,
                username=username,
                session=session,
                agent=agent,
                host=host,
                referer=referer,
                accept_language=accept_language,
                event=event,
                time=time,
                event_type=event_type,
                event_source=event_source,
                page=page
            )

        return JsonResponse(data)
class Migration(migrations.Migration):
    dependencies = [
        ('event_log', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(creat_event_logs_from_json),
    ]
